import type { CommandResult, VerificationResult } from "../../types/index.js";

export interface IncidentReportInput {
  incident_id: string;
  root_cause: string;
  detected_issue: string;
  command_results: CommandResult[];
  verification: VerificationResult;
  log_source?: string;
  started_at?: string;
}

export class ReporterService {
  generate(input: IncidentReportInput): string {
    const now = new Date().toISOString();
    const duration = this.calcDuration(input.started_at, now);
    const outcomeEmoji = input.verification.resolved ? "✅" : "⚠️";
    const outcome = input.verification.resolved ? "RESOLVED" : "UNRESOLVED";

    return [
      `# Incident Report — ${input.incident_id}`,
      ``,
      `## Overview`,
      `| Field | Value |`,
      `|---|---|`,
      `| **Status** | ${outcomeEmoji} ${outcome} |`,
      `| **Incident ID** | ${input.incident_id} |`,
      `| **Started** | ${input.started_at ?? "unknown"} |`,
      `| **Resolved** | ${now} |`,
      `| **Duration** | ${duration} |`,
      `| **Log Source** | ${input.log_source ?? "direct input"} |`,
      ``,
      `## Root Cause`,
      input.root_cause,
      ``,
      `## Detected Issue`,
      input.detected_issue,
      ``,
      `## Actions Taken`,
      this.formatCommands(input.command_results),
      ``,
      `## Verification`,
      this.formatVerification(input.verification),
      ``,
      `## Security`,
      `✔ All logs were locally redacted before AI processing.`,
      `✔ No credentials, tokens, or IPs were exposed externally.`,
      ``,
      `---`,
      `*Generated by ZeroTrust Log AI v2 — ${now}*`,
    ].join("\n");
  }

  private formatCommands(results: CommandResult[]): string {
    if (results.length === 0) return "No commands executed.";
    return results
      .map((r, i) => {
        const icon = r.success ? "✅" : "❌";
        const mode = r.dry_run ? "[DRY RUN]" : "[EXECUTED]";
        const timing = !r.dry_run && r.duration_ms > 0 ? ` (${r.duration_ms}ms)` : "";
        const output = r.output ? `\n   Output: ${r.output.slice(0, 200)}` : "";
        const err = r.error ? `\n   Error: ${r.error}` : "";
        return `${i + 1}. ${icon} ${mode} \`${r.command}\`${timing}${output}${err}`;
      })
      .join("\n");
  }

  private formatVerification(v: VerificationResult): string {
    const icon = v.resolved ? "✅" : "⚠️";
    const remaining =
      v.remaining_issues.length > 0
        ? `\nRemaining issues: ${v.remaining_issues.join(", ")}`
        : "";
    return `${icon} ${v.message}\nConfidence: ${v.confidence}${remaining}`;
  }

  private calcDuration(start?: string, end?: string): string {
    if (!start || !end) return "unknown";
    try {
      const ms = new Date(end).getTime() - new Date(start).getTime();
      if (ms < 60_000) return `${Math.round(ms / 1000)}s`;
      if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m`;
      return `${Math.round(ms / 3_600_000)}h`;
    } catch {
      return "unknown";
    }
  }
}
